language: node_js
node_js:
  - "6"

cache:
  directories:
    - "node_modules"

script:
  - rm -rf dist
  - npm run build:prod

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  repo: ChicagoWorldcon.github.io
  target-branch: master
  committer-from-gh: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
# poke for testing
