version: 0.1

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR/$CLIENT_SRC_DIR; npm install
      - echo '#!/bin/bash' > /usr/local/bin/ok; echo 'if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1; else exit 0; fi' >> /usr/local/bin/ok; chmod +x /usr/local/bin/ok

  pre_build:
    commands: []

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/$CLIENT_SRC_DIR; node_modules/.bin/webpack -p --progress --colors

  post_build:
    commands:
      - ok && cd $CODEBUILD_SRC_DIR/$CLIENT_SRC_DIR; aws s3 sync dist/ s3://$BUCKET_NAME/ --region $AWS_REGION --delete --acl public-read

cache:
  paths:
    - 'node_modules/**/*'
    - 'members-admin/node_modules/**/*'
